/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useEffect, useLayoutEffect } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import store from '../../store/store'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/all.gltf')

  const panneau = useRef();
  let posPanneau = useRef();


  useFrame(() => {
    var v = new THREE.Vector3();
    posPanneau = panneau.current.getWorldPosition(v);
    window.p = posPanneau; //{x: 32.26, y: 8.09, z: 22.27}
  })
  
  useEffect(() => {
    store.dispatch({type : 'PANEL POSITION', position : posPanneau})
  }, [posPanneau])

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={nodes.Lampadaire001.material}
        geometry={nodes.Lampadaire001.geometry}
        position={[-41.32, 8.98, -18.51]}
      />
      <mesh
        material={nodes.Lampadaire002.material}
        geometry={nodes.Lampadaire002.geometry}
        position={[15.37, 8.98, 17.76]}
      />
      <mesh
        material={nodes.Lampadaire003.material}
        geometry={nodes.Lampadaire003.geometry}
        position={[-33.11, 8.98, 40.75]}
      />
      <mesh material={materials['Bake-tex']} geometry={nodes.Plane.geometry} position={[0.77, 0, -0.56]} />
      <mesh material={materials['Matcap bleu']} geometry={nodes.Sphere.geometry} position={[4.76, 1.76, -20.23]} />
      <mesh material={materials['Matcap bleu']} geometry={nodes.bars.geometry} position={[65.02, 4.21, -57.14]} />
      <mesh material={materials['Matcap bleu']} geometry={nodes.Cardhu.geometry} position={[64.54, 4.89, -57.8]} />
      <mesh material={materials['Matcap bleu']} geometry={nodes.Circle002.geometry} position={[66.63, 8.68, -55.64]} />
      <mesh material={materials['Matcap bleu']} geometry={nodes.Cube035.geometry} position={[70.11, 4.48, -55.6]} />
      <mesh material={materials['Matcap bleu']} geometry={nodes.Cube036.geometry} position={[70.11, 4.48, -57.57]} />
      <mesh material={materials['Matcap bleu']} geometry={nodes.Cube037.geometry} position={[64.63, 1.01, -54.91]} />
      <mesh material={materials['Matcap bleu']} geometry={nodes.Cube038.geometry} position={[67.94, 1.01, -54.91]} />
      <mesh material={materials['Matcap bleu']} geometry={nodes.Cube039.geometry} position={[64.63, 1.01, -59.27]} />
      <mesh material={materials['Matcap bleu']} geometry={nodes.Cube040.geometry} position={[67.94, 1.01, -59.27]} />
      <mesh material={materials['Matcap bleu']} geometry={nodes.Cube042.geometry} position={[66.8, 6.25, -54.33]} />
      <mesh
        material={materials['Matcap bleu']}
        geometry={nodes.Glenkinchie.geometry}
        position={[64.81, 5.19, -58.32]}
      />
      <mesh
        material={materials['Matcap turquoise']}
        geometry={nodes.Sphere001.geometry}
        position={[8.65, 1.76, -20.23]}
      />
      <mesh
        material={materials['Matcap turquoise']}
        geometry={nodes.Cube004.geometry}
        position={[-2.91, -0.16, -56.57]}
      />
      <mesh
        material={materials['Matcap turquoise']}
        geometry={nodes.Plane006.geometry}
        position={[64.16, 12.29, -56.57]}
      />
      <mesh material={materials['Matcap jaune']} geometry={nodes.Sphere002.geometry} position={[12.8, 1.76, -20.23]} />
      <mesh material={materials['Matcap jaune']} geometry={nodes.Cube.geometry} position={[-60, 0, 0]} />
      <mesh material={materials['Matcap jaune']} geometry={nodes.Cube001.geometry} position={[60, 0, 0]} />
      <mesh material={materials['Matcap jaune']} geometry={nodes.Cube003.geometry} position={[30, 0, 60]} />
      <mesh
        material={materials['Matcap jaune']}
        geometry={nodes.BezierCurve.geometry}
        position={[64.98, 11.18, -55.57]}
      />
      <mesh material={materials['Matcap jaune']} geometry={nodes.Circle003.geometry} position={[67.07, 8.14, -54.18]} />
      <mesh material={materials['Matcap jaune']} geometry={nodes.Circle004.geometry} position={[64.17, 5.27, -56.89]} />
      <mesh
        material={materials['Matcap jaune']}
        geometry={nodes.Cylinder012.geometry}
        position={[64.38, 4.71, -58.58]}
      />
      <mesh
        material={materials['Matcap orange']}
        geometry={nodes.Sphere003.geometry}
        position={[16.65, 1.76, -20.23]}
      />
      <mesh material={materials['Matcap orange']} geometry={nodes.Cube055.geometry} position={[-60.72, 12.42, -0.7]} />
      <mesh material={materials['Matcap orange']} geometry={nodes.Cube047.geometry} position={[66.25, 2.75, -56.46]} />
      <mesh material={materials['Matcap orange']} geometry={nodes.Cube009.geometry} position={[66.68, 7.84, -57.07]} />
      <mesh material={materials['Matcap orange']} geometry={nodes.Cube041.geometry} position={[62.87, 4.12, -57.63]} />
      <mesh material={materials['Matcap orange']} geometry={nodes.Plane004.geometry} position={[65.3, 10.84, -55.67]} />
      <mesh material={materials['Matcap rouge']} geometry={nodes.Sphere004.geometry} position={[20.84, 1.76, -20.23]} />
      <mesh material={materials['Matcap rouge']} geometry={nodes.Cube002.geometry} position={[-30, 0, 60]} />
      <mesh material={materials['Matcap rouge']} geometry={nodes.breadHalf.geometry} position={[63.05, 4.27, -57.17]} />
      <mesh
        material={materials['Matcap rouge']}
        geometry={nodes.breadHalf001.geometry}
        position={[63.02, 4.23, -56.88]}
      />
      <mesh material={materials['Matcap rouge']} geometry={nodes.breadHalf003.geometry} position={[63.05, 4.27, -57]} />
      <mesh
        material={materials['Matcap rouge']}
        geometry={nodes.Cylinder011.geometry}
        position={[64.37, 4.47, -58.57]}
      />
      <mesh material={materials['Matcap rouge']} geometry={nodes.Plane002.geometry} position={[65.19, 11.05, -56.01]} />
      <mesh material={materials['Matcap rouge']} geometry={nodes.sausage.geometry} position={[63.31, 4.27, -57.25]} />
      <mesh material={materials['Matcap rouge']} geometry={nodes.sausage001.geometry} position={[63.03, 4.24, -58.1]} />
      <group position={[41.99, 3.47, -32.89]}>
        <mesh material={materials['Matcap orange']} geometry={nodes.Affiche1_0.geometry} />
        <mesh material={materials['Texture Tomato']} geometry={nodes.Affiche1_1.geometry} />
      </group>
      <mesh material={materials['Matcap beige']} geometry={nodes.Sphere005.geometry} position={[29.69, 1.76, -20.23]} />
      <mesh material={materials['Matcap beige']} geometry={nodes.Cube539.geometry} position={[9.08, 0.76, -33.68]} />
      <mesh material={materials['Matcap beige']} geometry={nodes.Cube006.geometry} position={[-47.75, 3.87, 3.87]} />
      <mesh material={materials['Matcap beige']} geometry={nodes.bread.geometry} position={[62.92, 4.27, -57.43]} />
      <mesh
        material={materials['Matcap beige']}
        geometry={nodes.breadHalf002.geometry}
        position={[63.26, 4.27, -57.77]}
      />
      <mesh material={materials['Matcap beige']} geometry={nodes.Circle008.geometry} position={[62.52, 4.12, -57.22]} />
      <mesh material={materials['Matcap beige']} geometry={nodes.Circle010.geometry} position={[62.53, 4.12, -57.85]} />
      <mesh
        material={materials['Matcap beige']}
        geometry={nodes.Cylinder020.geometry}
        position={[64.61, 11.53, -55.98]}
      />
      <mesh
        material={materials['Matcap beige']}
        geometry={nodes.Cylinder014.geometry}
        position={[66.08, 11.82, -55.44]}
      />
      <group position={[-27.79, 2.81, -20.17]}>
        <mesh material={materials['Matcap beige']} geometry={nodes['Cube.049_0'].geometry} />
        <mesh material={materials['Matcap marron']} geometry={nodes['Cube.049_1'].geometry} />
      </group>
      <mesh
        material={materials['Matcap marron']}
        geometry={nodes.Sphere006.geometry}
        position={[25.33, 1.76, -20.23]}
      />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube538.geometry} position={[13.69, 0.88, -33.8]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube053.geometry} position={[-60.95, 10.28, -0.11]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube054.geometry} position={[-60.95, 12.27, -0.11]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Circle005.geometry} position={[64.09, 5.42, -57]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube010.geometry} position={[68.44, 4.06, -57.07]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube011.geometry} position={[68.44, 1.42, -57.07]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube012.geometry} position={[63.93, 4.08, -56.61]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube013.geometry} position={[64, 1.42, -57.07]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube015.geometry} position={[66.24, 1.42, -59.27]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube016.geometry} position={[66.04, 4.09, -54.87]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube017.geometry} position={[66.55, 1.42, -54.89]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube021.geometry} position={[65.19, 6.22, -56.03]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube022.geometry} position={[65.07, 8.16, -57.2]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube023.geometry} position={[65.19, 6.84, -58.1]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube024.geometry} position={[62.89, 4.04, -57.07]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube025.geometry} position={[66.81, 6.06, -54.45]} />
      <mesh
        material={materials['Matcap marron']}
        geometry={nodes.Cube026.geometry}
        position={[66.81, -45.3, -116.31]}
      />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube027.geometry} position={[65.8, 7.52, -54.95]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube028.geometry} position={[67.81, 7.47, -54.96]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube029.geometry} position={[65.78, 5.92, -54.2]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube030.geometry} position={[67.81, 5.92, -54.6]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube031.geometry} position={[63.87, 2.62, -54.73]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube032.geometry} position={[63.89, 2.62, -59.45]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube033.geometry} position={[68.54, 2.89, -59.41]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube034.geometry} position={[68.55, 2.89, -54.77]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube043.geometry} position={[64.28, 4.5, -56.93]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube044.geometry} position={[63.3, 3.91, -54.84]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube045.geometry} position={[63.3, 3.91, -59.43]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube048.geometry} position={[68.69, 9.21, -55.49]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube049.geometry} position={[68.49, 8.72, -55.47]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube050.geometry} position={[68.69, 9.01, -58.42]} />
      <mesh material={materials['Matcap marron']} geometry={nodes.Cube051.geometry} position={[68.54, 8.59, -58.4]} />
      <mesh
        material={materials['Matcap marron']}
        geometry={nodes.Cylinder022.geometry}
        position={[64.13, 10.7, -56.26]}
      />
      <mesh
        material={materials['Matcap marron']}
        geometry={nodes.Cylinder021.geometry}
        position={[65.41, 11.82, -55.51]}
      />
      <mesh
        material={materials['Matcap marron']}
        geometry={nodes.Plane003.geometry}
        position={[64.78, 10.51, -56.34]}
      />
      <group position={[70.97, -45.33, -118.85]}>
        <mesh material={materials['Matcap marron']} geometry={nodes['Cube.068_0'].geometry} />
        <mesh material={materials['Matcap turquoise']} geometry={nodes['Cube.068_1'].geometry} />
      </group>
      <mesh
        material={materials['Matcap marron']}
        geometry={nodes.sausage002.geometry}
        position={[62.96, 4.26, -56.88]}
      />
      <mesh
        material={materials['Matcap marron']}
        geometry={nodes.sausage003.geometry}
        position={[63.09, 4.26, -56.85]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.shadeWhite003.geometry}
        position={[-39.08, 0.56, 13.44]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.Sphere008.geometry}
        position={[0.55, 1.76, -20.23]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.shadeWhite001.geometry}
        position={[-37.11, 0.56, 11.38]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.shadeWhite002.geometry}
        position={[-35.56, 0.56, 9.29]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.shadeWhite004.geometry}
        position={[-34.6, 0.56, 7.17]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.shadeWhite005.geometry}
        position={[-38.44, 1.61, 12.77]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.shadeWhite006.geometry}
        position={[-36.47, 1.61, 10.71]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.shadeWhite007.geometry}
        position={[-35.18, 1.61, 8.45]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.shadeWhite008.geometry}
        position={[-33.97, 1.25, 5.77]}
      />
      <group position={[-5.35, 1.07, 0]}>
        <mesh material={materials['Matcap orange']} geometry={nodes.defaultMaterial_0.geometry} />
        <mesh material={materials['Matcap marron']} geometry={nodes.defaultMaterial_1.geometry} />
        <mesh material={materials['Matcap bleu fonce']} geometry={nodes.defaultMaterial_2.geometry} />
      </group>
      <group position={[-62.8, 9.17, -0.34]}>
        <mesh material={materials['Matcap orange']} geometry={nodes['defaultMaterial.001_0'].geometry} />
        <mesh material={materials['Matcap marron']} geometry={nodes['defaultMaterial.001_1'].geometry} />
        <mesh material={materials['Matcap bleu fonce']} geometry={nodes['defaultMaterial.001_2'].geometry} />
      </group>
      <group position={[-59.19, 9.17, -0.13]}>
        <mesh material={materials['Matcap orange']} geometry={nodes['defaultMaterial.002_0'].geometry} />
        <mesh material={materials['Matcap marron']} geometry={nodes['defaultMaterial.002_1'].geometry} />
        <mesh material={materials['Matcap bleu fonce']} geometry={nodes['defaultMaterial.002_2'].geometry} />
      </group>
      <group position={[-60.9, 11.29, -0.13]}>
        <mesh material={materials['Matcap orange']} geometry={nodes['defaultMaterial.004_0'].geometry} />
        <mesh material={materials['Matcap marron']} geometry={nodes['defaultMaterial.004_1'].geometry} />
        <mesh material={materials['Matcap bleu fonce']} geometry={nodes['defaultMaterial.004_2'].geometry} />
      </group>
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.Cube005.geometry}
        position={[32.26, 2.3, 22.22]}
      />
      <group position={[32.26, 8.09, 22.27]}>
        <mesh material={materials['Matcap bleu fonce']} geometry={nodes.PanneauGeom_0.geometry} />
        <mesh ref={panneau} material={materials['Matcap bleu']} geometry={nodes.PanneauGeom_1.geometry} />
      </group>
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.Circle001.geometry}
        position={[68.34, 10.53, -55.08]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.Circle006.geometry}
        position={[64.15, 4.38, -55.93]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.Circle007.geometry}
        position={[64.17, 4.52, -55.82]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.Cube020.geometry}
        position={[66.18, 2.88, -54.56]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.Cylinder013.geometry}
        position={[70.63, 4.67, -56.68]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.Cylinder006.geometry}
        position={[66.2, 8.57, -55.12]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.Cylinder007.geometry}
        position={[67.94, 0.66, -54.91]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.Cylinder008.geometry}
        position={[64.63, 0.66, -54.91]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.Cylinder009.geometry}
        position={[64.63, 0.66, -59.27]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.Cylinder010.geometry}
        position={[67.94, 0.66, -59.27]}
      />
      <mesh
        material={materials['Matcap bleu fonce']}
        geometry={nodes.Torus003.geometry}
        position={[65.74, 9.4, -54.93]}
      />
      <mesh material={materials['Matcap blanc']} geometry={nodes.Sphere007.geometry} position={[33.87, 1.76, -20.23]} />
      <group position={[-36.25, 1.58, 2.08]}>
        <mesh material={materials['Matcap rouge']} geometry={nodes['Cone.001_0'].geometry} />
        <mesh material={materials['Matcap blanc']} geometry={nodes['Cone.001_1'].geometry} />
      </group>
      <group position={[-41.47, 1.58, -3.61]}>
        <mesh material={materials['Matcap rouge']} geometry={nodes['Cone.002_0'].geometry} />
        <mesh material={materials['Matcap blanc']} geometry={nodes['Cone.002_1'].geometry} />
      </group>
      <group position={[-38.46, 1.58, -2.34]}>
        <mesh material={materials['Matcap rouge']} geometry={nodes['Cone.003_0'].geometry} />
        <mesh material={materials['Matcap blanc']} geometry={nodes['Cone.003_1'].geometry} />
      </group>
      <mesh
        material={materials['Matcap blanc']}
        geometry={nodes.Cylinder073.geometry}
        position={[11.41, 0.99, -36.72]}
      />
      <mesh
        material={materials['Matcap blanc']}
        geometry={nodes.Cylinder001.geometry}
        position={[-3.32, 0.99, -36.72]}
      />
      <mesh
        material={materials['Matcap blanc']}
        geometry={nodes.Cylinder002.geometry}
        position={[-14.18, 0.99, -36.72]}
      />
      <mesh
        material={materials['Matcap blanc']}
        geometry={nodes.Cylinder003.geometry}
        position={[16.85, 0.99, -42.36]}
      />
      <mesh
        material={materials['Matcap blanc']}
        geometry={nodes.Cylinder004.geometry}
        position={[16.85, 0.99, -56.54]}
      />
      <mesh
        material={materials['Matcap blanc']}
        geometry={nodes.Cylinder005.geometry}
        position={[16.85, 0.99, -67.59]}
      />
      <group position={[-27.62, 0.93, -52.6]}>
        <mesh material={materials['Matcap blanc']} geometry={nodes['Cylinder.090_0'].geometry} />
        <mesh material={materials['Matcap marron']} geometry={nodes['Cylinder.090_1'].geometry} />
        <mesh material={materials['Matcap turquoise']} geometry={nodes['Cylinder.090_2'].geometry} />
      </group>
      <group position={[1.01, 0.72, -13.76]}>
        <mesh material={materials['Matcap rouge']} geometry={nodes['Cube.017_0'].geometry} />
        <mesh material={materials['Matcap blanc']} geometry={nodes['Cube.017_1'].geometry} />
        <mesh material={materials['Matcap marron']} geometry={nodes['Cube.017_2'].geometry} />
      </group>
      <group position={[-58.64, 4.45, 0.45]}>
        <mesh material={materials['Matcap marron']} geometry={nodes['8_Material #38_0.001_0'].geometry} />
        <mesh material={materials['Matcap blanc']} geometry={nodes['8_Material #38_0.001_1'].geometry} />
        <mesh material={materials['Matcap bleu']} geometry={nodes['8_Material #38_0.001_2'].geometry} />
        <mesh material={materials['Matcap rouge']} geometry={nodes['8_Material #38_0.001_3'].geometry} />
        <mesh material={materials['Matcap bleu']} geometry={nodes['8_Material #38_0.001_4'].geometry} />
        <mesh material={materials['Matcap jaune']} geometry={nodes['8_Material #38_0.001_5'].geometry} />
        <mesh material={materials['Matcap jaune']} geometry={nodes['8_Material #38_0.001_6'].geometry} />
      </group>
      <group position={[2.33, 0.72, -12.02]}>
        <mesh material={materials['Matcap rouge']} geometry={nodes['Cube.153_0'].geometry} />
        <mesh material={materials['Matcap blanc']} geometry={nodes['Cube.153_1'].geometry} />
        <mesh material={materials['Matcap marron']} geometry={nodes['Cube.153_2'].geometry} />
      </group>
      <group position={[5.54, 0.72, -13.85]}>
        <mesh material={materials['Matcap rouge']} geometry={nodes['Cube.154_0'].geometry} />
        <mesh material={materials['Matcap blanc']} geometry={nodes['Cube.154_1'].geometry} />
        <mesh material={materials['Matcap marron']} geometry={nodes['Cube.154_2'].geometry} />
      </group>
      <group position={[23.07, 1.98, 0]}>
        <mesh material={materials['Matcap blanc']} geometry={nodes['Cube.161_0'].geometry} />
        <mesh material={materials['Matcap rouge']} geometry={nodes['Cube.161_1'].geometry} />
      </group>
      <group position={[-66.66, 8.17, -54.58]}>
        <mesh material={materials['Matcap bleu']} geometry={nodes['Cylinder.052_0'].geometry} />
        <mesh material={materials['Matcap marron']} geometry={nodes['Cylinder.052_1'].geometry} />
        <mesh material={materials['Matcap beige']} geometry={nodes['Cylinder.052_2'].geometry} />
        <mesh material={materials['Matcap blanc']} geometry={nodes['Cylinder.052_3'].geometry} />
      </group>
      <group position={[-60.8, 14.16, 2.35]}>
        <mesh material={materials['Matcap beige']} geometry={nodes['Cube.162_0'].geometry} />
        <mesh material={materials['Matcap bleu']} geometry={nodes['Cube.162_1'].geometry} />
        <mesh material={materials['Matcap bleu fonce']} geometry={nodes['Cube.162_2'].geometry} />
        <mesh material={materials['Matcap rouge']} geometry={nodes['Cube.162_3'].geometry} />
        <mesh material={materials['Matcap blanc']} geometry={nodes['Cube.162_4'].geometry} />
      </group>
      <mesh
        material={materials['Matcap blanc']}
        geometry={nodes.Object_20001.geometry}
        position={[-71.1, 1.34, -39.59]}
      />
      <mesh
        material={materials['Matcap blanc']}
        geometry={nodes.Object_20002.geometry}
        position={[-78.73, 1.34, -37.44]}
      />
      <group position={[-62.93, 6.37, -38.3]}>
        <mesh material={materials['Matcap jaune']} geometry={nodes['Cube.165_0'].geometry} />
        <mesh material={materials['Matcap bleu fonce']} geometry={nodes['Cube.165_1'].geometry} />
        <mesh material={materials['Matcap blanc']} geometry={nodes['Cube.165_2'].geometry} />
      </group>
      <group position={[-51.56, 1.82, -41.67]}>
        <mesh material={materials['Matcap rouge']} geometry={nodes['Cone.007_0'].geometry} />
        <mesh material={materials['Matcap blanc']} geometry={nodes['Cone.007_1'].geometry} />
      </group>
      <mesh material={materials['Matcap blanc']} geometry={nodes.Plane005.geometry} position={[63.72, 12.93, -56.84]} />
      <mesh
        material={materials['shadeWhite.001']}
        geometry={nodes.shadeWhite_015.geometry}
        position={[-25.08, 0.14, -18.11]}
      />
      <mesh
        material={materials['Faisceau.001']}
        geometry={nodes.Faisceau001.geometry}
        position={[-41.32, 1.37, -18.51]}
      />
      <mesh
        material={materials['Faisceau.001']}
        geometry={nodes.Faisceau002.geometry}
        position={[15.37, 1.37, 17.76]}
      />
      <mesh
        material={materials['Faisceau.001']}
        geometry={nodes.Faisceau003.geometry}
        position={[-33.11, 1.37, 40.75]}
      />
      <group position={[55.76, 3.47, 15.54]}>
        <mesh material={materials['Texture Cap']} geometry={nodes.Affiche2_0.geometry} />
        <mesh material={materials['Matcap orange']} geometry={nodes.Affiche2_1.geometry} />
        <mesh material={materials['Matcap rouge']} geometry={nodes.Affiche2_2.geometry} />
      </group>
      <group position={[-34.25, 4.19, -93.41]}>
        <mesh material={materials['Texture Aquerelle 2']} geometry={nodes['Cube.006_0'].geometry} />
        <mesh material={materials['Matcap marron']} geometry={nodes['Cube.006_1'].geometry} />
        <mesh material={materials['Texture Aquerelle 3']} geometry={nodes['Cube.006_2'].geometry} />
        <mesh material={materials['Texture Aquerellle 4']} geometry={nodes['Cube.006_3'].geometry} />
        <mesh material={materials['Texture Aquerellle 5']} geometry={nodes['Cube.006_4'].geometry} />
      </group>
      <group position={[-24.16, 3.47, -32.89]}>
        <mesh material={materials['Texture Obsolete']} geometry={nodes['Affiche2.001_0'].geometry} />
        <mesh material={materials['Matcap orange']} geometry={nodes['Affiche2.001_1'].geometry} />
        <mesh material={materials['Matcap rouge']} geometry={nodes['Affiche2.001_2'].geometry} />
      </group>
      <mesh material={materials['cheese01.001']} geometry={nodes.Circle009.geometry} position={[62.76, 3.95, -56.48]} />
      <mesh
        material={materials['Glass Simple.001']}
        geometry={nodes.Cube019.geometry}
        position={[66.25, 2.75, -54.61]}
      />
      <group position={[50.09, 4.18, -62]}>
        <mesh material={materials['Matcap bleu']} geometry={nodes['BezierCurve.002_0'].geometry} />
        <mesh material={materials['Matcap marron']} geometry={nodes['BezierCurve.002_1'].geometry} />
        <mesh material={materials['Matcap bleu fonce']} geometry={nodes['BezierCurve.002_2'].geometry} />
        <mesh material={materials['Matcap jaune']} geometry={nodes['BezierCurve.002_3'].geometry} />
        <mesh material={materials['Glass Simple.001']} geometry={nodes['BezierCurve.002_4'].geometry} />
        <mesh material={materials['Matcap orange']} geometry={nodes['BezierCurve.002_5'].geometry} />
        <mesh material={materials['Matcap turquoise']} geometry={nodes['BezierCurve.002_6'].geometry} />
      </group>
    </group>
  )
}
