/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/arcade.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials['Material_38.001']} geometry={nodes['8_Material #38_0.001_0'].geometry} />
      <mesh material={materials['Material_41.001']} geometry={nodes['8_Material #38_0.001_1'].geometry} />
      <mesh material={materials['Material_39.001']} geometry={nodes['8_Material #38_0.001_2'].geometry} />
      <mesh material={materials['Material_42.001']} geometry={nodes['8_Material #38_0.001_3'].geometry} />
      <mesh material={materials['Material_56.001']} geometry={nodes['8_Material #38_0.001_4'].geometry} />
      <mesh material={materials['Material_40.001']} geometry={nodes['8_Material #38_0.001_5'].geometry} />
    </group>
  )
}
