/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { useSphere, useBox } from 'use-cannon'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/cloud.gltf')

  const [cloud, cloudApi] = useBox(() => ({
    mass : 1,
    args : [2,2,2]

  }))

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh ref={cloud} material={materials.nuageMat} geometry={nodes.Cloud.geometry} >
        <mesh material={materials.VolantMat} geometry={nodes.car_body000.geometry} />
        <mesh material={materials.VolantMat} geometry={nodes.car_body015.geometry}  />
        <mesh material={materials.VolantMat} geometry={nodes.Manche_volant.geometry}  />
      </mesh>
    </group>
  )
}
