/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/essai.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={nodes.wLF.material} geometry={nodes.wLF.geometry} position={[-1.31, 1.27, 2.38]} />
      <mesh material={nodes.wRF.material} geometry={nodes.wRF.geometry} position={[1.28, 1.27, 2.38]} />
      <mesh material={nodes.wBL.material} geometry={nodes.wBL.geometry} position={[-1.31, -1.27, 2.38]} />
      <mesh material={nodes.wBR.material} geometry={nodes.wBR.geometry} position={[1.28, -1.27, 2.38]} />
      <mesh material={nodes.obstacle.material} geometry={nodes.obstacle.geometry} position={[0, 18.74, 1]} />
      <mesh material={materials.Material} geometry={nodes.Cube.geometry} position={[0, 0, 2.86]} />
      <mesh material={materials['Material.001']} geometry={nodes.Plane.geometry} />
    </group>
  )
}
