/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import store from '../../store/store'
import { Provider, useSelector } from "react-redux";


export default function IdeaList (props) {
  const ideaList = useSelector((state) => state.assets.idea);
  return (
      
        ideaList.map((a, i) => {
        return (<Idea position={[Math.random()* 2 * i, i * Math.random() * 2 , i * Math.random() * 2]} key={i} ideaId={i} title={a.title} msg={a.msg} name={a.name} args={[2,2,2]} />)
      })
      
  );
};

const Idea = (props) => {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/ampoule.gltf')
  return (
    <group ref={group} {...props} dispose={null} onClick={() => {
      store.dispatch({type : "OPEN MODAL"})
      store.dispatch({type : 'CHANGE CONTENT', content : 'showidea'})
      store.dispatch({type : 'CHANGE ID IDEA', ideaId : props.ideaId})
    }}>
      <mesh material={materials['Matcap jaune']} geometry={nodes['Sphere.011_0'].geometry} />
      <mesh material={materials['Matcap orange']} geometry={nodes['Sphere.011_1'].geometry} />
      <mesh material={materials['Matcap bleu fonce']} geometry={nodes['Sphere.011_2'].geometry} />
    </group>
  )
}
