/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Infos(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/infos.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
        <mesh material={materials['Matcap bleu']} geometry={nodes['Cube.008_0'].geometry} />
        <mesh material={materials['Matcap bleu fonce']} geometry={nodes['Cube.008_1'].geometry} />
        <mesh material={materials['Matcap blanc']} geometry={nodes['Cube.008_2'].geometry} />
    </group>
  )
}
