/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import Master from "../gltf/essai.glb";
import store from '../../store/store'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, Master)
  const cube =useRef()

  useFrame((state, delta) => {
  let pos = store.getState().profile.positionSocket[store.getState().profile.id]
  cube.current.position.set(pos.x, pos.y, pos.z)
  window.cube = cube.current.position
  }
  )

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={nodes.Plane.material} geometry={nodes.Plane.geometry} scale={[6.59, 6.59, 6.59]} />
      <mesh ref={cube} material={materials.Material} geometry={nodes.Cube.geometry} position={[0, 7.24, 0]} />
    </group>
  )
}
