/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import React, { useRef } from 'react';
import { useLoader } from 'react-three-fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import useStore from '../../store/zstore';


export default function MsgList (props) {
  const msgList = useStore(state => state.message)
  return (
      
        msgList.map((a, i) => {
        return (<Msg position={[-10.76, 2.56, -45.49 - i * 2]} key={i} msgId={i} title={a.title} msg={a.msg} name={a.name} args={[2,2,2]} />)
      })
      
  );
};

const Msg = (props) => {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/msg.gltf')
  const changeId = useStore(state => state.changeId);
  const changeContent = useStore(state => state.changeContent)
  const togglePop = useStore(state => state.togglePop)


  return (
    <group ref={group} {...props} dispose={null} onClick={() => {
      togglePop();
      changeContent('showmsg');
      changeId(props.msgId);
    }}>
      <group>
        <mesh material={materials['Matcap beige']} geometry={nodes['Cube.025_0'].geometry} />
        <mesh material={materials['Matcap marron']} geometry={nodes['Cube.025_1'].geometry} />
      </group>
    </group>
  )
}
