/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import store from '../../store/store'
import { Provider, useSelector } from "react-redux";


export default function MsgList (props) {
  const msgList = useSelector((state) => state.assets.msg);
  return (
      
        msgList.map((a, i) => {
        return (<Msg position={[-10.76, 2.56, -45.49 - i * 2]} key={i} msgId={i} title={a.title} msg={a.msg} name={a.name} args={[2,2,2]} />)
      })
      
  );
};

const Msg = (props) => {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/msg.gltf')
  return (
    <group ref={group} {...props} dispose={null} onClick={() => {
      store.dispatch({type : "OPEN MODAL"})
      store.dispatch({type : 'CHANGE CONTENT', content : 'showmsg'})
      store.dispatch({type : 'CHANGE ID MSG', msgId : props.msgId})
    }}>
      <group>
        <mesh material={materials['Matcap beige']} geometry={nodes['Cube.025_0'].geometry} />
        <mesh material={materials['Matcap marron']} geometry={nodes['Cube.025_1'].geometry} />
      </group>
    </group>
  )
}
