/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/passive.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={nodes.Affiche_1.material} geometry={nodes.Affiche_1.geometry} position={[27.13, 3.47, -32.89]} />
      <mesh material={nodes.Affiche_2.material} geometry={nodes.Affiche_2.geometry} position={[55.76, 3.47, 15.54]} />
      <mesh material={nodes.Affiche_3.material} geometry={nodes.Affiche_3.geometry} position={[-24.16, 3.47, -32.89]} />
      <mesh material={nodes.Arcade.material} geometry={nodes.Arcade.geometry} position={[-58.64, 4.45, 0.45]} />
      <mesh
        material={nodes.Bloc_beton.material}
        geometry={nodes.Bloc_beton.geometry}
        position={[-72.96, 4.38, -85.15]}
      />
      <mesh
        material={nodes.Building_construction.material}
        geometry={nodes.Building_construction.geometry}
        position={[-66.66, 8.09, -54.58]}
      />
      <mesh material={nodes.Camion.material} geometry={nodes.Camion.geometry} position={[41.84, 3.13, -47.41]} />
      <mesh material={nodes.Carblock.material} geometry={nodes.Carblock.geometry} position={[-50.86, 2.64, 14.3]} />
      <mesh
        material={nodes.BarriereBetton.material}
        geometry={nodes.BarriereBetton.geometry}
        position={[-71.1, 1.34, -39.59]}
      />
      <mesh
        material={nodes.BarriereBetton2.material}
        geometry={nodes.BarriereBetton2.geometry}
        position={[-78.73, 1.34, -37.44]}
      />
      <mesh material={nodes.Button.material} geometry={nodes.Button.geometry} position={[87.77, 3.03, 20.72]} />
      <mesh
        material={nodes.CubeBetton.material}
        geometry={nodes.CubeBetton.geometry}
        position={[-20.12, 6.37, 79.42]}
      />
      <mesh
        material={nodes.CubeBetton2.material}
        geometry={nodes.CubeBetton2.geometry}
        position={[-62.93, 6.37, -38.3]}
      />
      <mesh
        material={nodes.GardenBarriere.material}
        geometry={nodes.GardenBarriere.geometry}
        position={[7.41, 0.99, -46.11]}
      />
      <mesh
        material={nodes.ConcreteBanc.material}
        geometry={nodes.ConcreteBanc.geometry}
        position={[-3.01, 1.51, -73.99]}
      />
      <mesh
        material={nodes.CrateCamera.material}
        geometry={nodes.CrateCamera.geometry}
        position={[-60.96, 9.88, -0.2]}
      />
      <mesh
        material={nodes.GardenSign.material}
        geometry={nodes.GardenSign.geometry}
        position={[-0.05, 2.56, -45.49]}
      />
      <mesh
        material={nodes.GiantPanel.material}
        geometry={nodes.GiantPanel.geometry}
        position={[-27.79, 2.74, -20.2]}
      />
      <mesh material={nodes.Grue.material} geometry={nodes.Grue.geometry} position={[-44.82, 29.63, -64.26]} />
      <mesh material={nodes.Herb.material} geometry={nodes.Herb.geometry} position={[-20.71, 0.23, -17.33]} />
      <mesh material={nodes.Jardin.material} geometry={nodes.Jardin.geometry} position={[-2.91, 0.14, -56.57]} />
      <mesh material={nodes.MailBox.material} geometry={nodes.MailBox.geometry} position={[17.37, 2.41, 36.69]} />
      <mesh material={nodes.AdSign.material} geometry={nodes.AdSign.geometry} position={[-43.49, 2.4, 14.3]} />
      <mesh
        material={nodes.PlancheArcade.material}
        geometry={nodes.PlancheArcade.geometry}
        position={[-47.75, 3.87, 3.87]}
      />
      <mesh
        material={nodes.PlancheCamera.material}
        geometry={nodes.PlancheCamera.geometry}
        position={[-60.95, 10.28, -0.11]}
      />
      <mesh
        material={nodes.PlancheCamera2.material}
        geometry={nodes.PlancheCamera2.geometry}
        position={[-60.95, 12.27, -0.11]}
      />
      <mesh
        material={nodes.PlancheCamera3.material}
        geometry={nodes.PlancheCamera3.geometry}
        position={[-60.72, 12.42, -0.7]}
      />
      <mesh
        material={nodes.PlancheTram.material}
        geometry={nodes.PlancheTram.geometry}
        position={[-9.33, 1.72, 43.24]}
      />
      <mesh material={nodes.radio.material} geometry={nodes.radio.geometry} position={[44.76, 3.45, -45.23]} />
      <mesh material={nodes.Screen.material} geometry={nodes.Screen.geometry} position={[-67.97, 14.85, -42.57]} />
      <mesh
        material={nodes.TeteBarriere.material}
        geometry={nodes.TeteBarriere.geometry}
        position={[29.55, 0.99, 65.99]}
      />
      <mesh material={nodes.Text1.material} geometry={nodes.Text1.geometry} position={[-24.87, 4.42, 64.17]} />
      <mesh material={nodes.Text2.material} geometry={nodes.Text2.geometry} position={[-15.97, 6.06, 44.58]} />
      <mesh material={nodes.Text3.material} geometry={nodes.Text3.geometry} position={[-23.04, 6, 73.38]} />
      <mesh material={nodes.Tram.material} geometry={nodes.Tram.geometry} position={[-18.33, 4.16, 44.24]} />
      <mesh material={nodes.Tree.material} geometry={nodes.Tree.geometry} position={[55.77, 0.93, 46.4]} />
      <mesh material={nodes.Tree2.material} geometry={nodes.Tree2.geometry} position={[-27.62, 0.93, -52.6]} />
      <mesh material={nodes.Trottoir.material} geometry={nodes.Trottoir.geometry} position={[-60, 0, 0]} />
      <mesh material={nodes.Trottoir1.material} geometry={nodes.Trottoir1.geometry} position={[60, 0, 0]} />
      <mesh material={nodes.Trottoir3.material} geometry={nodes.Trottoir3.geometry} position={[29.55, 0.13, 66.05]} />
      <mesh material={nodes.Trottoir5.material} geometry={nodes.Trottoir5.geometry} position={[17.33, -0.06, 37.16]} />
      <mesh
        material={nodes.TrottoirCamion.material}
        geometry={nodes.TrottoirCamion.geometry}
        position={[44.23, -0.06, -44.69]}
      />
      <mesh material={nodes.WoodenBanc.material} geometry={nodes.WoodenBanc.geometry} position={[13.69, 0.88, -33.8]} />
    </group>
  )
}
