/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import { PositionalAudio } from 'drei'
import React, { useRef } from 'react'
import { useFrame, useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'



export default function Radio(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/radio.gltf')
  const pAudio = useRef()
  useFrame(() =>   window.pan = pAudio.current
  )
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials['Matcap turquoise']} geometry={nodes.radio_0.geometry} />
      <mesh material={materials['Matcap bleu fonce']} geometry={nodes.radio_1.geometry} />
      <mesh material={materials['Matcap beige']} geometry={nodes.radio_2.geometry} />
      <mesh material={materials['Matcap rouge']} geometry={nodes.radio_3.geometry} >
      <PositionalAudio position={[44,5,-44]} ref={pAudio} url={props.url} distance={4} loop={false}  />
      </mesh>
    </group>
  )
}
