/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/railsjoin.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Camera} />
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      </group>
      <group position={[337.21, -52.97, -19.61]}>
        <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry}>
          <mesh material={materials['Acier brun']} geometry={nodes.traverse.geometry} />
        </mesh>
      </group>
      <group position={[7.87, -32.56, -15.07]}>
        <mesh material={nodes.Lampadaire.material} geometry={nodes.Lampadaire.geometry} />
        <mesh material={materials.Faisceau} geometry={nodes.Faisceau.geometry} />
      </group>
      <group position={[7.87, -32.56, -15.07]}>
        <mesh material={nodes.Lampadaire.material} geometry={nodes.Lampadaire.geometry} />
        <mesh material={materials.Faisceau} geometry={nodes.Faisceau.geometry} />
      </group>
      <group position={[7.87, -32.56, -15.07]}>
        <mesh material={nodes.Lampadaire.material} geometry={nodes.Lampadaire.geometry} />
        <mesh material={materials.Faisceau} geometry={nodes.Faisceau.geometry} />
      </group>
      <group position={[7.87, -32.56, -15.07]}>
        <mesh material={nodes.Lampadaire.material} geometry={nodes.Lampadaire.geometry} />
        <mesh material={materials.Faisceau} geometry={nodes.Faisceau.geometry} />
      </group>
      <mesh material={nodes.dworzec.material} geometry={nodes.dworzec.geometry} />
      <mesh material={nodes.Cube077.material} geometry={nodes.Cube077.geometry} />
      <mesh material={nodes.kosciol1.material} geometry={nodes.kosciol1.geometry} />
      <mesh material={nodes.Bridge.material} geometry={nodes.Bridge.geometry} />
      <mesh material={nodes.dom_opata.material} geometry={nodes.dom_opata.geometry} />
      <mesh material={nodes.kopalnia.material} geometry={nodes.kopalnia.geometry} />
      <mesh material={nodes.Cube288.material} geometry={nodes.Cube288.geometry} />
      <mesh material={nodes.Circle120.material} geometry={nodes.Circle120.geometry}>
        <mesh material={nodes.Cube540.material} geometry={nodes.Cube540.geometry} />
      </mesh>
      <mesh material={nodes.Cube538.material} geometry={nodes.Cube538.geometry} />
      <mesh material={nodes.Cube539.material} geometry={nodes.Cube539.geometry} />
      <mesh material={nodes.Cube541.material} geometry={nodes.Cube541.geometry} />
      <mesh material={nodes.Cylinder070.material} geometry={nodes.Cylinder070.geometry} />
      <mesh material={nodes.Cylinder072.material} geometry={nodes.Cylinder072.geometry} />
      <mesh material={nodes.Cylinder073.material} geometry={nodes.Cylinder073.geometry} />
      <mesh material={nodes.Tour.material} geometry={nodes.Tour.geometry} />
      <mesh material={nodes.Lampadaire.material} geometry={nodes.Lampadaire.geometry} />
      <mesh material={nodes.glasplanes.material} geometry={nodes.glasplanes.geometry} />
      <mesh material={nodes.mainbody.material} geometry={nodes.mainbody.geometry} />
      <mesh material={nodes.poster.material} geometry={nodes.poster.geometry} />
      <mesh material={nodes.roof.material} geometry={nodes.roof.geometry} />
      <mesh material={nodes.screws.material} geometry={nodes.screws.geometry} />
      <mesh material={nodes.seat.material} geometry={nodes.seat.geometry} />
      <mesh material={nodes.shield.material} geometry={nodes.shield.geometry} />
      <mesh material={nodes.sign.material} geometry={nodes.sign.geometry} />
      <mesh material={nodes.streetinternetbox.material} geometry={nodes.streetinternetbox.geometry} />
      <mesh material={nodes.trashcan.material} geometry={nodes.trashcan.geometry} />
      <mesh material={nodes.trashcanmetal.material} geometry={nodes.trashcanmetal.geometry} />
      <mesh material={nodes.trashcantorus.material} geometry={nodes.trashcantorus.geometry} />
      <mesh material={nodes.trashcanwood.material} geometry={nodes.trashcanwood.geometry} />
      <mesh material={nodes.MARCO001.material} geometry={nodes.MARCO001.geometry}>
        <mesh material={nodes['AFICHE-B001'].material} geometry={nodes['AFICHE-B001'].geometry} />
        <mesh material={nodes.BASE001.material} geometry={nodes.BASE001.geometry} />
        <mesh material={nodes.TUBOS_de_LUZ001.material} geometry={nodes.TUBOS_de_LUZ001.geometry} />
        <mesh material={materials.luz} geometry={nodes.Plane007.geometry} />
      </mesh>
      <mesh material={materials['Material.001']} geometry={nodes.Cone.geometry} />
      <mesh material={materials['Material.015']} geometry={nodes['Plane.001_0'].geometry} />
      <mesh material={materials['Material.016']} geometry={nodes['Plane.001_1'].geometry} />
      <mesh material={materials['Material.017']} geometry={nodes['Plane.001_2'].geometry} />
      <mesh material={materials['Material.018']} geometry={nodes.Rails001.geometry} />
      <group position={[-7.87, 32.56, 1.32]}>
        <mesh material={materials['Material.015']} geometry={nodes['Plane.005_0'].geometry} />
        <mesh material={materials['Material.016']} geometry={nodes['Plane.005_1'].geometry} />
        <mesh material={materials['Material.017']} geometry={nodes['Plane.005_2'].geometry} />
      </group>
      <mesh material={materials.Green} geometry={nodes.Sol.geometry} />
      <mesh material={materials['Acier brun']} geometry={nodes.Poteau.geometry} />
      <mesh material={materials.Faisceau} geometry={nodes.Faisceau.geometry} />
      <mesh material={materials.shadeWhite} geometry={nodes.shadeWhite119.geometry} />
      <mesh material={materials.shadeWhite} geometry={nodes.shadeWhite001.geometry} />
      <mesh material={materials.shadeWhite} geometry={nodes.shadeWhite002.geometry} />
      <mesh material={materials.shadeWhite} geometry={nodes.shadeWhite003.geometry} />
      <mesh material={materials.shadeWhite} geometry={nodes.shadeWhite004.geometry} />
      <mesh material={materials['shadeWhite.001']} geometry={nodes.shadeWhite_002.geometry} />
      <mesh material={materials['shadeWhite.001']} geometry={nodes.shadeWhite_015.geometry} />
      <mesh material={materials['shadeWhite.001']} geometry={nodes.shadeWhite_015002.geometry} />
      <mesh material={materials.shadeBeige} geometry={nodes.shadeBeige001.geometry} />
    </group>
  )
}
