/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Town(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/town.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['Material.033']}
        geometry={nodes.bldgs2001.geometry}
        position={[56.93, 10.59, -111.68]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.16, 0.16, 0.16]}
      />
      <mesh
        material={materials['Material.031']}
        geometry={nodes.bldgs2002.geometry}
        position={[85.51, 25.87, -33.51]}
        rotation={[Math.PI / 2, 0, 1.18]}
        scale={[0.22, 0.22, 0.22]}
      />
      <mesh
        material={materials['Material.010']}
        geometry={nodes.building1_6.geometry}
        position={[119.33, -0.33, 59.4]}
        rotation={[0, 1.56, 0]}
        scale={[6.32, 6.32, 6.32]}
      />
      <mesh
        material={materials['Material.013']}
        geometry={nodes.building1_9.geometry}
        position={[4.62, -1.04, -124.04]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[9.19, 9.19, 9.19]}
      />
      <mesh
        material={materials['Material.016']}
        geometry={nodes.building3_3.geometry}
        position={[66.92, -0.38, 94.35]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[4.21, 4.21, 4.21]}
      />
      <mesh
        material={materials['Material.046']}
        geometry={nodes.Cube005.geometry}
        position={[-64.68, 4.97, 102.17]}
        rotation={[0, 1.57, 0]}
        scale={[9.16, 5.01, 8.01]}
      />
      <mesh
        material={materials['Material.037']}
        geometry={nodes.Cube009.geometry}
        position={[-139.5, 11.25, 12.16]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[16.07, 4.16, 16.07]}
      />
      <mesh
        material={materials['Material.035']}
        geometry={nodes.Cube010.geometry}
        position={[93.29, 8.19, 70.03]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[3.65, 8.4, 8.9]}
      />
      <mesh
        material={materials['Material.038']}
        geometry={nodes.Cube011.geometry}
        position={[96.12, 7.86, 42.31]}
        scale={[6.31, 7.92, 9.47]}
      />
      <mesh
        material={materials['Material.039']}
        geometry={nodes.Cylinder006.geometry}
        position={[-156.6, 54.71, 71.06]}
        rotation={[0, -0.44, 0]}
        scale={[7.53, 18.21, 10.57]}
      />
      <mesh
        material={materials['Material.045']}
        geometry={nodes.Plane003.geometry}
        position={[-126.86, 34.07, -83.69]}
        rotation={[0, 1.57, 0]}
        scale={[3.16, 4.74, 3.16]}
      />
      <mesh
        material={materials['Material.043']}
        geometry={nodes.Plane005.geometry}
        position={[3.88, -1.7, 114.87]}
        scale={[14.09, 10.11, 10.11]}
      />
    </group>
  )
}
