/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef, useState } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import jeepModel from './jeep.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, jeepModel)
  const [increase, setIncrease] = useState(true);
  useFrame(state => {
    let maxY = 5;
    let minY = 2;
    let y = group.current.position.y;
    if (y < maxY && increase) {
      group.current.position.y += 0.010;
    } else if (y === maxY) {
      console.log("now decrease");
    }
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="Scene">
        <group name="Carosserie">
          <mesh material={materials.carbody} geometry={nodes.Cube_0.geometry} name="Cube_0" />
          <mesh material={materials.windows} geometry={nodes.Cube_1.geometry} name="Cube_1" />
          <mesh material={materials.Lights} geometry={nodes.Cube_2.geometry} name="Cube_2" />
          <mesh material={materials.Tail} geometry={nodes.Cube_3.geometry} name="Cube_3" />
          <mesh material={materials.grill} geometry={nodes.Cube_4.geometry} name="Cube_4" />
        </group>
        <group name="RouesAV">
          <mesh material={materials.carbody} geometry={nodes['Cube.001_0'].geometry} name="Cube.001_0" />
          <mesh material={materials.tires} geometry={nodes['Cube.001_1'].geometry} name="Cube.001_1" />
          <mesh material={materials.Rim} geometry={nodes['Cube.001_2'].geometry} name="Cube.001_2" />
        </group>
        <group name="RouesAR">
          <mesh material={materials.carbody} geometry={nodes['Cube.002_0'].geometry} name="Cube.002_0" />
          <mesh material={materials['tires.001']} geometry={nodes['Cube.002_1'].geometry} name="Cube.002_1" />
          <mesh material={materials.rim} geometry={nodes['Cube.002_2'].geometry} name="Cube.002_2" />
        </group>
        <group name="RoueS" position={[4.91, -1.6, -5.75]} rotation={[-0.01, 0, -0.01]}>
          <mesh material={materials.carbody} geometry={nodes['Cube.003_0'].geometry} name="Cube.003_0" />
          <mesh material={materials['tires.002']} geometry={nodes['Cube.003_1'].geometry} name="Cube.003_1" />
          <mesh material={materials['Material.001']} geometry={nodes['Cube.003_2'].geometry} name="Cube.003_2" />
        </group>
        <mesh material={materials['rails.001']} geometry={nodes.Coffre.geometry} name="Coffre" />
        <mesh material={materials.roofrack} geometry={nodes.PorteBagages.geometry} name="PorteBagages" />
      </scene>
    </group>
  )
}
