/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import SceneModel from './scene.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, SceneModel)  
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Camera} />
      <group position={[-25.22, 0, 1.74]}>
        <mesh
          material={materials.nuageMat}
          geometry={nodes.Sphere000.geometry}
          position={[1.54, -0.01, 0.41]}
          scale={[0.63, 0.63, 0.63]}
        />
        <mesh
          material={materials.nuageMat}
          geometry={nodes.Sphere006.geometry}
          position={[-1.05, 0, 0.14]}
          scale={[0.41, 0.41, 0.41]}
        />
        <mesh
          material={materials.nuageMat}
          geometry={nodes.Sphere010.geometry}
          position={[0.43, 0, -0.03]}
          scale={[0.6, 0.6, 0.6]}
        />
        <mesh
          material={materials.nuageMat}
          geometry={nodes.Sphere011.geometry}
          position={[-0.44, 0, -0.17]}
          scale={[0.71, 0.71, 0.71]}
        />
        <mesh
          material={materials.nuageMat}
          geometry={nodes.Sphere002.geometry}
          position={[0.52, -0.52, 0]}
          scale={[0.52, 0.52, 0.52]}
        />
        <mesh
          material={materials.nuageMat}
          geometry={nodes.Sphere003.geometry}
          position={[-0.13, -0.93, -0.39]}
          scale={[0.46, 0.46, 0.46]}
        />
        <mesh
          material={materials.nuageMat}
          geometry={nodes.Sphere004.geometry}
          position={[-0.5, -0.52, 0.34]}
          scale={[0.64, 0.64, 0.64]}
        />
        <mesh
          material={materials.nuageMat}
          geometry={nodes.Sphere007.geometry}
          position={[1.2, -0.52, 0]}
          scale={[0.61, 0.61, 0.61]}
        />
        <mesh
          material={materials.nuageMat}
          geometry={nodes.Sphere008.geometry}
          position={[0.12, -0.67, 0.41]}
          scale={[0.34, 0.34, 0.34]}
        />
        <mesh
          material={materials.nuageMat}
          geometry={nodes.Sphere009.geometry}
          position={[0.53, -0.73, -0.53]}
          scale={[0.34, 0.34, 0.34]}
        />
      </group>
      <group position={[-25.22, 3.99, 1.74]}>
        <mesh
          material={materials.nuageMat}
          geometry={nodes.carMesh.geometry}
          position={[-0.44, 0, -0.17]}
          scale={[0.71, 0.71, 0.71]}
        />
      </group>
      <mesh material={materials.Material} geometry={nodes.Gabarit_1m.geometry} position={[-83.39, -95.2, 0.5]} />
      <mesh material={materials.shadeOrange} geometry={nodes.Plane.geometry} />
      <mesh
        material={materials.Batiment}
        geometry={nodes.Batiment.geometry}
        position={[0, 0, 6]}
        scale={[0.67, 0.67, 0.6]}
      />
      <mesh
        material={materials.Bus}
        geometry={nodes.Batiment001.geometry}
        position={[38.34, 18.81, 1.25]}
        rotation={[0, 0, -0.66]}
      />
      <mesh
        material={materials.trottoir}
        geometry={nodes.Batiment002.geometry}
        position={[0, 0, 0.17]}
        scale={[1.36, 1.36, 0.02]}
      />
      <mesh material={materials.Floor} geometry={nodes.Plane001.geometry} />
    </group>
  )
}
