/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import {useBox} from 'use-cannon'

import SolModel from './sol.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, SolModel )
  const [ref] = useBox(() => ({ ...props }))


  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="Scene">
        <mesh ref={ref} material={materials.Sol} geometry={nodes.Plane.geometry} name="Plane" scale={[20, 20, 20]} />
      </scene>
    </group>
  )
}
